'use strict';

var React = require('react-native');

module.exports = {
    questionsDrink: [
        'Cuantos elementos tiene la tabla periodica?',
        'Cuantos continentes hay en el mundo?',
        'cuantos mares hay en el mundo?',
        '3 paises por la letra M',
        'Cuantas peliculas hay de harry potter?',
        'Rio mas largo del mundo',
        'Cuantos estados tiene USA',
        'Donde se encuentra el monumento de la operda de sidney',
        'Empresa mas rica del mundo',
        'Idioma mas hablado del mundo',
        'Pais mas grande del mundo',
        'Numero exacto de PI',
        'Capital de cuba',
        'Capital de alemania',
        'Como se llama la hembra del caballo',
        'Triangulo con 7 lados',
        'Que planeta esta mas cerca del sol',
        'Animal mas grande del mundo',
        'Organo mas grande del ser humano',
        'Pais donde seran las proximas olimpiadas',
        'Cuantos jugadores juegan en un partido de beisbol',
        'Nombre de 4 presidentes actuales',
        'Ganador actual del mis universo',
        '3 frutas verdes',
        '3 pelicas dode salga la roca',
        'Pelicula ganadora del oscar',
        'Persona mas seguida en instagran',
        'Nacionalidad del actual papa',
        'Como se llama el perro  en la comiquita Tom y Jerry',
        'Animal que mata mas personas en el mundo',
        'Como se escribe 63 en numeros romanos',
        'Quien pinto el cuadro de la ultima cena',
        'Quien fue Nicolas Tesla',
        'Colores de bandera de rusia'
    ],
    never:[
        'Viaje a mas de 2 paises',
        'Te han sido infiel',
        'Fuiste infiel',
        'Salido con alguien con pareja',
        'Te han estafado',
        'Fumado mariguana',
        'Mentido para irte de fiesta',
        'Usado algun yeso por fractura',
        'Te han operado',
        'Peleado a golpes',
        'Usado un juguete sexual',
        'Usado un juguete sexual',
        'Tattuado',
        'Ido a parque acuatico',
        'Preparado una paella ',
        'Caminado por mas de 6 horas consecutivas',
        'Tuviste sexo al lado de alguien',
        'Llorado el ultimo mes',
        'Haz ido a ver un partido en vivo de futbol profesional',
        'Discutido con alguien desconocido en la calle',
        'Ido por mas de 6 meses al gym',
        'Perdido mis llaves',
        'Haz vomitado en una fiesta',
        'Haz robado algo ',
        'Haz sentido estar humillado por amor',
        'Te han pillado haciendo algo de debias',
        'Haz dejado a alguien plantado o cancelaste a ultimo minuto',
        'Te has acostado con alguien y lo has ignorado después',
        'Haz pedido foto o autografo a algun famoso',
        'Haz hecho pis en una piscina',
        'Bloqueado a alguien de redes',
        'Pagado productos como onlyfans',
        'Manejado moto',
        'Te haz orinado en la cama',
        'Te han despedido de algun trabajo',
        'Haz sido mala copa',
    ]
} 