'use strict';

var React = require('react-native');

module.exports = {
    questionsDrink: [
        'Cuantos elementos tiene la tabla periodica?',
        'Cuantos continentes hay en el mundo?',
        'cuantos mares hay en el mundo?',
        '3 paises por la letra M',
        'Cuantas peliculas hay de harry potter?',
        'Rio mas largo del mundo',
        'Cuantos estados tiene USA',
        'Donde se encuentra el monumento de la operda de sidney',
        'Empresa mas rica del mundo',
        'Idioma mas hablado del mundo',
        'Pais mas grande del mundo',
        'Numero exacto de PI',
        'Capital de cuba',
        'Capital de alemania',
        'Como se llama la hembra del caballo',
        'Triangulo con 7 lados',
        'Que planeta esta mas cerca del sol',
        'Animal mas grande del mundo',
        'Organo mas grande del ser humano',
        'Pais donde seran las proximas olimpiadas',
        'Cuantos jugadores juegan en un partido de beisbol',
        'Nombre de 4 presidentes actuales',
        'Ganador actual del mis universo',
        '3 frutas verdes',
        '3 pelicas dode salga la roca',
        'Pelicula ganadora del oscar',
        'Persona mas seguida en instagran',
        'Nacionalidad del actual papa',
        'Como se llama el perro  en la comiquita Tom y Jerry',
        'Animal que mata mas personas en el mundo',
        'Como se escribe 63 en numeros romanos',
        'Quien pinto el cuadro de la ultima cena',
        'Quien fue Nicolas Tesla',
        'Colores de bandera de rusia'
    ],
    never:[
        'Viaje a mas de 2 paises',
        'Te han sido infiel',
        'Fuiste infiel',
        'Salido con alguien con pareja',
        'Te han estafado',
        'Fumado mariguana',
        'Mentido para irte de fiesta',
        'Usado algun yeso por fractura',
        'Te han operado',
        'Peleado a golpes',
        'Usado un juguete sexual',
        'Usado un juguete sexual',
        'Tattuado',
        'Ido a parque acuatico',
        'Preparado una paella ',
        'Caminado por mas de 6 horas consecutivas',
        'Tuviste sexo al lado de alguien',
        'Llorado el ultimo mes',
        'Haz ido a ver un partido en vivo de futbol profesional',
        'Discutido con alguien desconocido en la calle',
        'Ido por mas de 6 meses al gym',
        'Perdido mis llaves',
        'Haz vomitado en una fiesta',
        'Haz robado algo ',
        'Haz sentido estar humillado por amor',
        'Te han pillado haciendo algo de debias',
        'Haz dejado a alguien plantado o cancelaste a ultimo minuto',
        'Te has acostado con alguien y lo has ignorado después',
        'Haz pedido foto o autografo a algun famoso',
        'Haz hecho pis en una piscina',
        'Bloqueado a alguien de redes',
        'Pagado productos como onlyfans',
        'Manejado moto',
        'Te haz orinado en la cama',
        'Te han despedido de algun trabajo',
        'Haz sido mala copa',
    ],
    hot:[
        'Toma 2 shot',
        '¿Tendrías relaciones con alguien de este grupo?',
        '¿Has tenido relaciones con alguien de este grupo?',
        '¿Quién es la persona más sexy aquí?',
        '¿Alguna vez has pensado en engañar a una pareja tuya?',
        '¿Quién de las personas de este grupo tiene el cuerpo más bonito?',
        '¿Cuál es tu posición sexual favorita?',
        '¿Has tenido relaciones con un desconocido/a?',
        '¿Has tenido sexo en la calle?',
        '¿Alguna vez te han sorprendido teniendo sexo?',
        '¿Alguna vez has dudado de tu orientación sexual?',
        '¿Has quedado con alguien que has conocido en Internet?',
        '¿Con cuántas personas te has acostado?',
        'De este grupo, ¿a quién besarías antes?',
        '¿Alguna vez te has olvidado del nombre de la persona con la que te has acostado?',
        '¿Alguna vez has tenido sexo en la cama de tus padres?',
        '¿Cuál es el mejor lugar para hacerlo?',
        '¿Cómo te describirías en la cama?',
        '¿Cuál es el peor sexo que has tenido en tu vida?',
        '¿Has tenido algún sueño erótico con alguien de aquí?',
        '¿Alguna vez has hecho un trío?',
        '¿Con qué dos personas de aquí harías un trío?',
        '¿Qué es algo que nunca te has atrevido a pedir en la cama?',
        'Da una vuelta en ropa interior por la calle.',
        'Tírate a la piscina con ropa.',
        'Sirve las copas de todo el mundo durante toda la noche.',
        'No mires el móvil durante dos horas.',
        'Haz tantas flexiones como puedas en un minuto.',
        'Deja que alguien del grupo lea tus mensajes.',
        'Publica una foto en la que salgas mal en Instagram.',
        'Llama a tu última pareja y dile que le echas de menos.',
        'Imita a alguien del grupo.',
        'Actúa representando la escena de una película.',
        'Huélele el pie a alguien del grupo.',
        'Quítale la camiseta a alguien del grupo.',
        'Lámele el cuello a una persona del grupo.',
        'Dale un beso a la persona de tu derecha.',
        'Manda un mensaje a uno de tus ex insultándolo.',
        'Cómete un ajo crudo masticándolo.',
        'Llama a alguien y dile que estás embarazada.',
        'Acábate todo el vaso de alcohol.',
        'Pásale el hielo a alguien del grupo sin utilizar las manos.',
        'Tírale piropos a un amigo y a ver cómo responde',
        'Actúa representando la escena de una película.',
    ]
} 